# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: msdemo
services:
  app:
    image: msdemo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
